esp8266:
  board: d1_mini


esphome:
  name: doorbell
  friendly_name: Deurbel
  project:
    name: zuidwijk.doorbell
    version: "2.0"

packages:
  always: !include common/always.yaml
  wifi: !include common/wifi.yaml 
 
# Enable Home Assistant API
api:
 
time:
  - platform: homeassistant
    id: homeassistant_time
 
text_sensor:
  - platform: version
    name: ESPHome Version
 
sensor:
  - platform: uptime
    name: Uptime
 
globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: 'true'
 
button:
  - platform: restart
    name: Restart
  - platform: template
    name: Test
    on_press:
      - logger.log: 'Test Button Pressed'
      - switch.turn_on: relay
      - delay: 5s
      - switch.turn_off: relay

switch:
  - platform: gpio
    name: "Relay"
    id: relay
    pin:
      number: D1
      inverted: false
    internal: true
    icon: mdi:alarm-bell
  - platform: template
    name: Chime Active
    id: chime_active
    restore_mode: DISABLED
    turn_on_action:
      - globals.set:
          id: chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: chime
          value: 'false'
    lambda: |-
      return id(chime);
     
binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: true
    name: Bell
    filters:
      # Small filter, to debounce the button press.
      # - delayed_on: 25ms
      - delayed_off: 3000ms
    on_press:
      # Only turn on the chime when it is active.
      then:
        if:
          condition:
            - switch.is_on: chime_active
          then:
            - switch.turn_on: relay
            - delay: 500ms
            - switch.turn_off: relay
 
  - platform: status
    name: Status
