substitutions:
  name: esp32-bluetooth-proxy-eea580
  friendly_name: Bluetooth Proxy eea580
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: bngS+/V1H67YwdWVfo8eseWK1dX9+o7iZbgIXtaaORE=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
