substitutions:
  name: m5stack-atom-echo-24090c
  friendly_name: M5Stack Atom Echo 24090c

packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: wZTiPffB4HQwSEGrjku9Dt7ThS+qudihICUyNEea/i8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
