substitutions:
  name: waterlezer

packages:
  smartstuff.waterlezer: github://mhendriks/esphome-p1/waterlezer.yaml
  always: !include common/always.yaml
  wifi: !include common/wifi.yaml
  
esphome:
  name: ${name}
  name_add_mac_suffix: false

api:
  encryption:
    key: aeB2W3aw/6dAnqYp4JXV89abcvTHko8QGpcRVQn/y3E=
