esp8266:
  board: esp01_1m


esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}


packages:
  always: !include always.yaml # ota & logger
  wifi: !include wifi.yaml


api:


output:
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_red
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_green
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_blue
