esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

packages:
  always: !include always.yaml
  wifi: !include wifi.yaml

api:

output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r

light:
  - platform: rgb
    id: ledstrip
    name: "${friendly_name} Led Strip"
    red: pwm_r
    green: pwm_g
    blue: pwm_b

