
globals:
  - id: display_page
    type: int
    restore_value: no
    initial_value: '1'


esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: -10
    then:
      - wait_until:
          api.connected:
      - logger.log: API is connected
      - rtttl.play: "success:d=24,o=5,b=100:c,g,b"
      - switch.template.publish:
          id: ticker_on_off
          state: ON
  includes:
    - common/slideclock.h
    - common/slidefont_all.h

packages:
  always: !include always.yaml
  wifi: !include wifi.yaml
  mqtt: !include mqtt.yaml
  hardware: !include ticker-hardware.yaml

api:
  services:
  - service: play_rtttl
    variables:
      song_str: string
    then:
      - rtttl.play: !lambda 'return song_str;'
  - service: display_next_page
    then:
      - script.execute: display_next_page
  - service: display_page
    variables:
      page: int
    then:
      - globals.set:
          id: display_page
          value: !lambda 'return page;'
      - component.update: ticker_display
  - service: alert
    variables:
      text: string
      sound: bool
    then:
      - script.execute: display_alert

time:
  - platform: homeassistant
    id: hass_time


text_sensor:
  - platform: homeassistant
    id: text
    entity_id: input_text.${devicename}_text
  - platform: homeassistant
    id: person_martijn
    entity_id: person.martijn_donath
  - platform: homeassistant
    id: person_veerle
    entity_id: person.veerle
  - platform: homeassistant
    id: person_marjolein
    entity_id: person.marjolein
  - platform: homeassistant
    id: person_abel
    entity_id: person.abel
  - platform: homeassistant
    id: internet_abel
    internal: True
    entity_id: group.internet_devices_abel
  - platform: homeassistant
    id: internet_marjolein
    internal: True
    entity_id: group.internet_devices_marjolein
  - platform: homeassistant
    id: internet_veerle
    internal: True
    entity_id: group.internet_devices_veerle

sensor:
  - platform: homeassistant
    id: current_power_usage
    internal: True
    entity_id: sensor.power_consumption
  - platform: homeassistant
    id: brightness
    name: ${friendly_name} Brightness
    entity_id: input_number.${devicename}_brightness
    accuracy_decimals: 0
  - platform: homeassistant
    id: scroll_mode
    name: ${friendly_name} Scroll Mode
    entity_id: input_number.${devicename}_scroll_mode
    accuracy_decimals: 0
  - platform: homeassistant
    id: scroll_speed
    name: ${friendly_name} Scroll Speed
    entity_id: input_number.${devicename}_scroll_speed
    accuracy_decimals: 0
  - platform: homeassistant
    id: scroll_delay
    name: ${friendly_name} Scroll Delay
    entity_id: input_number.${devicename}_scroll_delay
    accuracy_decimals: 0
  - platform: homeassistant
    id: scroll_dwell
    name: ${friendly_name} Scroll Dwell
    entity_id: input_number.${devicename}_scroll_dwell
    accuracy_decimals: 0

switch:
  - platform: template
    name: ${friendly_name}
    id: ticker_on_off
    icon: "mdi:clock-digital"
    restore_state: True
    turn_off_action:
      - switch.template.publish:
          id: ticker_on_off
          state: OFF
      - script.execute: display_page0
    turn_on_action:
      - switch.template.publish:
          id: ticker_on_off
          state: ON
      - script.execute: display_page1

button:
  - platform: template
    name: ${friendly_name} Next Page
    on_press:
      then:
        - script.execute: display_next_page

script:
  - id: display_next_page
    then:
      - logger.log: "Script display next page"
      - if:
          condition:
            switch.is_on: ticker_on_off
          then:
            - lambda: |-
                if (id(display_page) < 6) {
                  id(display_page) += 1;
                } else {
                  id(display_page) = 1;
                }
            - component.update: ticker_display
  - id: display_page0
    then:
      - logger.log: "Script display page 0"
      - globals.set:
          id: display_page
          value: '0'
      - component.update: ticker_display
  - id: display_page1
    then:
      - logger.log: "Script display page 1"
      - if:
          condition:
            switch.is_on: ticker_on_off
          then:
            - globals.set:
                id: display_page
                value: '1'
            - component.update: ticker_display
  - id: display_page2
    then:
      - logger.log: "Script display page 2"
      - if:
          condition:
            switch.is_on: ticker_on_off
          then:
            - globals.set:
                id: display_page
                value: '2'
            - component.update: ticker_display
  - id: display_page3
    then:
      - logger.log: "Script display page 3"
      - if:
          condition:
            switch.is_on: ticker_on_off
          then:
            - globals.set:
                id: display_page
                value: '3'
            - component.update: ticker_display
  - id: display_page4
    then:
      - logger.log: "Script display page 4"
      - if:
          condition:
            switch.is_on: ticker_on_off
          then:
            - globals.set:
                id: display_page
                value: '4'
            - component.update: ticker_display
  - id: display_page5
    then:
      - logger.log: "Script display page 5"
      - if:
          condition:
            switch.is_on: ticker_on_off
          then:
            - globals.set:
                id: display_page
                value: '5'
            - component.update: ticker_display
  - id: display_alert
    then:
      - logger.log: "ALERT!"
  - id: action_button
    then:
      - if:
          condition:
            lambda: 'return id(display_page) == 1;'
          then:
            - lambda: |-
                id(brightness).publish_state(0);
            
      - if:
          condition:
            lambda: 'return id(display_page) == 2;'
          then:
            - rtttl.play: "success:d=24,o=5,b=100:c,c,c"
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.h801_abel_led_strip
                  effect: Flash van Ledstrip
